image: docker:latest

variables:
  DOCKER_REGISTRY: $AWS_ECR_REGISTRY/$CI_PROJECT_NAME/main
  DEPLOY_TYPE: ""
  SERVER_IP: ""
  SERVER_KEY: ""
  ENV_VARIABLES: ""
  COMMON_ENV_VARIABLES: ""
  DEPLOY_CLUSTER_NAME: ""
  DEPLOY_NAMESPACE_NAME: ""
  IS_CRON: $DEPLOY_IS_CRON
  RELEASE_TAG: "false"
  IS_HOTFIX: "false"

workflow:
  rules:
    - if:  '$CI_PROJECT_ROOT_NAMESPACE == "credflow" && $CI_COMMIT_BRANCH == "dev"' # Dev env
      variables:
        DEPLOY_TYPE: "DEV"
        SERVER_IP: $DEV_SERVER_IP
        SERVER_KEY: $DEV_SERVER_KEY
        ENV_VARIABLES: $DEV_ENV_VARIABLES
        COMMON_ENV_VARIABLES: $DEV_COMMON_ENV_VARIABLES
        DOCKER_REGISTRY: "$AWS_ECR_REGISTRY/$CI_PROJECT_NAME/dev"
        DOCKER_BUILD_TAG: $CI_COMMIT_BRANCH
    - if: '$CI_PROJECT_ROOT_NAMESPACE == "credflow" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master")' # QA env
      variables:
        DEPLOY_TYPE: "QA"
        SERVER_IP: ""
        SERVER_KEY: $STAGING_PROD_SERVER_KEY
        ENV_VARIABLES: $STAGING_PROD_ENV_VARIABLES
        COMMON_ENV_VARIABLES: $STAGING_PROD_COMMON_ENV_VARIABLES
        DEPLOY_CLUSTER_NAME: $STAGING_PROD_CLUSTER_NAME
        DEPLOY_NAMESPACE_NAME: $STAGING_PROD_NAMESPACE_NAME
    - if: '$CI_COMMIT_TAG =~ /-release/' # Prod env
      variables:
        RELEASE_TAG: "true"
        DEPLOY_TYPE: "MASTER"
        SERVER_IP: ""
        SERVER_KEY: $MASTER_SERVER_KEY
        ENV_VARIABLES: $MASTER_ENV_VARIABLES
        COMMON_ENV_VARIABLES: $MASTER_COMMON_ENV_VARIABLES
        DEPLOY_CLUSTER_NAME: $MASTER_CLUSTER_NAME
        DEPLOY_NAMESPACE_NAME: $MASTER_NAMESPACE_NAME
    - if: '$CI_COMMIT_TAG =~ /-uat/' # UAT env
      variables:
        RELEASE_TAG: "true"
        DEPLOY_TYPE: "UAT"
        SERVER_IP: ""
        SERVER_KEY: $UAT_SERVER_KEY
        ENV_VARIABLES: $UAT_ENV_VARIABLES
        COMMON_ENV_VARIABLES: $UAT_COMMON_ENV_VARIABLES
        DEPLOY_CLUSTER_NAME: $UAT_CLUSTER_NAME
        DEPLOY_NAMESPACE_NAME: $UAT_NAMESPACE_NAME
    - if: '$CI_COMMIT_BRANCH =~ /main-hotfix-/' # Hotfix in prod env
      variables:
        IS_HOTFIX: "true"
        DEPLOY_TYPE: "MASTER"
        SERVER_IP: ""
        SERVER_KEY: $MASTER_SERVER_KEY
        ENV_VARIABLES: $MASTER_ENV_VARIABLES
        COMMON_ENV_VARIABLES: $MASTER_COMMON_ENV_VARIABLES
        DEPLOY_CLUSTER_NAME: $MASTER_CLUSTER_NAME
        DEPLOY_NAMESPACE_NAME: $MASTER_NAMESPACE_NAME
    - when: always

stages:
  - build

build:
  stage: build
  image: 841835653837.dkr.ecr.ap-south-1.amazonaws.com/aws-docker:2.0.0
  services:
    - name: docker:dind
  before_script:
    - aws --version
    - docker --version
    - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY
  script:
    - VERSION=1.0.0
    - docker build -t $DOCKER_REGISTRY .
    - docker tag $DOCKER_REGISTRY $DOCKER_REGISTRY:$VERSION
    - docker push $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY:$VERSION
  rules:
    - if: '($DEPLOY_TYPE != "" && $RELEASE_TAG == "false")|| $IS_HOTFIX == "true"'
      when: on_success